config/routes.rb
Splitsdb::Application.routes.draw do 
  resources :authentications

  get '/login'  => 'users#new'
  get '/login/twitch'      => 'user_sessions#twitch_login'
  get '/login/twitch/auth' => 'user_sessions#twitch_auth'

  get '/signup' => 'users#new'
  get '/logout' => 'user_sessions#destroy'
  get '/upload' => 'runs#new'
  get '/games'  => 'games#index'
  post '/games' => 'games#create'

  get '/users/:id' => 'users#show', :as => :user
  get '/users/:id/edit' => 'users#edit', :as => :edit_user
  get '/:id/delete' => 'games#destroy'
  get '/:game_id/:category_id/runs/:id/compare/:compare_id' => 'runs#show', :as => :compare
  get '/:game_id/:category_id/runs/:id/download' => 'runs#download_exact'
  get '/:game_id/:category_id/runs/:id/delete' => 'runs#destroy'
  #get '/:game_id/:category_id/runs/:id/download-route' => 'runs#download_blank'
  post '/:game_id/:category_id/runs/:id/edit' => 'runs#edit'

  root 'static_pages#home'

  resources :users do
    resources :runs
  end
  resources :games, :path => ''
  resources :games, :path => '', :only => [] do
    resources :categories, :path => '' do
      resources :runs
    end
    #get :autocomplete_game_name, :on => :collection
  end

  post '/:game_id/:category_id/runs/:id' => 'runs#compare'
#  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_action :set_authentication, only: [:show, :edit, :update, :destroy]

  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = current_user.authentications if current_user
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
  end

  # GET /authentications/new
  def new
    @authentication = Authentication.new
  end

  # GET /authentications/1/edit
  def edit
  end

  # POST /authentications
  # POST /authentications.json
  def create
    @authentication = Authentication.new(authentication_params)

    respond_to do |format|
      if @authentication.save
        format.html { redirect_to @authentication, notice: 'Authentication was successfully created.' }
        format.json { render action: 'show', status: :created, location: @authentication }
      else
        format.html { render action: 'new' }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authentications/1
  # PATCH/PUT /authentications/1.json
  def update
    respond_to do |format|
      if @authentication.update(authentication_params)
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication.destroy
    respond_to do |format|
      format.html { redirect_to authentications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authentication
      @authentication = Authentication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authentication_params
      params.require(:authentication).permit(:user_id, :provider, :uid, :index, :create, :destroy)
    end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.haml
= form_for @authentication do |f|
  - if @authentication.errors.any?
    #error_explanation
      %h2= "#{pluralize(@authentication.errors.count, "error")} prohibited this authentication from being saved:"
      %ul
        - @authentication.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :uid
    = f.text_field :uid
  .field
    = f.label :index
    = f.text_field :index
  .field
    = f.label :create
    = f.text_field :create
  .field
    = f.label :destroy
    = f.text_field :destroy
  .actions
    = f.submit 'Save'

app/views/authentications/edit.html.haml
%h1 Editing authentication

= render 'form'

= link_to 'Show', @authentication
\|
= link_to 'Back', authentications_path

app/views/authentications/index.html.haml
%h1 Listing authentications

%table
  %tr
    %th User
    %th Provider
    %th Uid
    %th Index
    %th Create
    %th Destroy
    %th
    %th
    %th

  - @authentications.each do |authentication|
    %tr
      %td= authentication.user_id
      %td= authentication.provider
      %td= authentication.uid
      %td= authentication.index
      %td= authentication.create
      %td= authentication.destroy
      %td= link_to 'Show', authentication
      %td= link_to 'Edit', edit_authentication_path(authentication)
      %td= link_to 'Destroy', authentication, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Authentication', new_authentication_path

app/views/authentications/new.html.haml
%h1 New authentication

= render 'form'

= link_to 'Back', authentications_path

app/views/authentications/show.html.haml
%p#notice= notice

%p
  %b User:
  = @authentication.user_id
%p
  %b Provider:
  = @authentication.provider
%p
  %b Uid:
  = @authentication.uid
%p
  %b Index:
  = @authentication.index
%p
  %b Create:
  = @authentication.create
%p
  %b Destroy:
  = @authentication.destroy

= link_to 'Edit', edit_authentication_path(@authentication)
\|
= link_to 'Back', authentications_path