config/routes.rb
Splitsdb::Application.routes.draw do 
  resources :authentications

  get '/login'  => 'users#new'
  get '/login/twitch'      => 'user_sessions#twitch_login'
  get '/login/twitch/auth' => 'user_sessions#twitch_auth'

  get '/signup' => 'users#new'
  get '/logout' => 'user_sessions#destroy'
  get '/upload' => 'runs#new'
  get '/games'  => 'games#index'
  post '/games' => 'games#create'

  get '/users/:id' => 'users#show', :as => :user
  get '/users/:id/edit' => 'users#edit', :as => :edit_user
  get '/:id/delete' => 'games#destroy'
  get '/:game_id/:category_id/runs/:id/compare/:compare_id' => 'runs#show', :as => :compare
  get '/:game_id/:category_id/runs/:id/download' => 'runs#download_exact'
  get '/:game_id/:category_id/runs/:id/delete' => 'runs#destroy'
  #get '/:game_id/:category_id/runs/:id/download-route' => 'runs#download_blank'
  post '/:game_id/:category_id/runs/:id/edit' => 'runs#edit'

  root 'static_pages#home'

  resources :users do
    resources :runs
  end
  resources :games, :path => ''
  resources :games, :path => '', :only => [] do
    resources :categories, :path => '' do
      resources :runs
    end
    #get :autocomplete_game_name, :on => :collection
  end

  post '/:game_id/:category_id/runs/:id' => 'runs#compare'
#  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  acts_as_authentic
  has_many :authentications
  has_many :runs
  has_many :games, through: :runs, :uniq => true
  has_many :categories, through: :runs, :uniq => true
  validates_presence_of :email, :password, :name, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    if user_params[:action] == 'signup'
      @user = User.create(user_params.except(:action))
      @session = UserSession.create(:email => user_params[:email], :password => user_params[:password], :remember_me => true)
      respond_to do |format|
        if @user.save
          format.html { redirect_to '/', notice: 'Account created! Welcome, ' + @user.name + '.' }
          format.json { render action: 'show', status: :created, location: @user }
        else
          format.html { redirect_to action: 'new' }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
      @session = UserSession.create(:email => user_params[:email], :password => user_params[:password], :remember_me => true)
      respond_to do |format|
        if @session.save
          format.html { redirect_to root_path, notice: "Welcome, #{current_user.name}. You're logged in!" }
          format.json { render action: 'show', location: current_user }
        else
          format.html { redirect_to login_path, alert: 'Incorrect email or password.' }
          format.json { render json: current_user.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:action, :email, :name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
%h1 Edit account info

= form_for @user, url: {action: :update} do |f|
  .form-group

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Email
    %th Handle
    %th Password
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.email
      %td= user.handle
      %td= user.password
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
.col-md-6
  - if request.fullpath == '/signup'
    %h1#title Sign up
  - else
    %h1#title Log in / sign up

  = form_for @user, url: {action: "create"} do |f|
    - if @user.errors.any?
      .alert.alert-danger
        %b= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        %ul
          - @user.errors.full_messages.each do |msg|
            %li= msg
    .form-group
      %input.form-control.input-lg{:name => "user[email]", :placeholder => "Email", :type => "text", :autofocus => (request.fullpath == '/signup' || request.fullpath == '/login'), :value => @user.email }/
    .form-group
      %input.form-control{:name => "user[password]", :placeholder => "Password", :type => "password"}/
    - if !current_user.present?
      .radio
        %label
          - if request.fullpath != '/signup'
            %input#optionsRadios1{:checked => "", :name => "user[action]", :type => "radio", :value => "login", :onclick => "$('h1#title').html('Log in'); document.getElementById('sign-up').style.display = 'none'; document.getElementById('submit').value = 'Log in '; window.history.replaceState('', 'Title', 'login');"}/
          - else
            %input#optionsRadios1{:name => "user[action]", :type => "radio", :value => "login", :onclick => "$('h1#title').html('Log in'); document.getElementById('sign-up').style.display = 'none'; document.getElementById('submit').value = 'Log in '; window.history.replaceState('', 'Title', 'login');"}/
          I have an account and want to log in
      .radio
        %label
          - if request.fullpath == '/signup'
            %input#optionsRadios2{:checked => "", :name => "user[action]", :type => "radio", :value => "signup", :onclick => "$('h1#title').html('Sign up'); document.getElementById('sign-up').style.display = 'block'; document.getElementById('submit').value = 'Sign up'; window.history.replaceState('', 'Title', 'signup');"}/
          - else
            %input#optionsRadios2{:name => "user[action]", :type => "radio", :value => "signup", :onclick => "$('h1#title').html('Sign up'); document.getElementById('sign-up').style.display = 'block'; document.getElementById('submit').value = 'Sign up'; window.history.replaceState('', 'Title', 'signup');"}/
          I want to make a new account
    #sign-up{:style => "#{'display: none;' if request.fullpath != '/signup' && !current_user}"}
      .form-group
        %input.form-control{:name => "user[password_confirmation]", :placeholder => "Confirm password", :type => "password"}/
      .form-group
        %input.form-control{:name => "user[name]", :placeholder => "Choose a name", :type => "text", :value => @user.name}/
    .actions
      %input#submit.btn.btn-default{:name => :commit, :type => :submit, :value => "#{request.fullpath == '/signup' ? 'Sign up' : request.fullpath == '/login' ? 'Log in' : 'Update'}"}
.col-md-6
  %h1 Log in with Twitch
  %center{style: 'margin-top: 60px;'}
    %a.twitch-button{href: '/login/twitch'}
      %img{src: 'http://s.jtvnw.net/jtv_user_pictures/hosted_images/GlitchIcon_white.png', style: 'width: 18px; height: 18px; margin-right: 2px;'}
      Log in with Twitch

app/views/users/show.html.haml
.row
  %h1
    =@user.name
    - if @user == current_user
      %small
        %a{:href => edit_user_path(@user)}
          .glyphicon.glyphicon-pencil
.row
  %h2 Games run by #{@user.name}
  - @user.games.each do |game|
    .col-md-3
      %a.thumbnail{:href => game_path(game)}
        %img{:alt => game.name, "src" => "#{game.cover}"}/
.row
  %h2 Recent runs by #{@user.name}
  .panel.panel-default
    %table.table.table-striped.table-hover{:style => "border-top: none;"}
      %tr{:style => "border-top: none;"}
        %td{:style => "border-top: none;"}
          %b="Game"
        %td{:style => "border-top: none;"}
          %b="Category"
        %td{:style => "border-top: none;"}
          %b="Finish time"
      - @user.runs[0,6].each do |run|
        %tr{:onclick => "document.location = '#{game_category_run_path(run.game, run.category, run)}'", :style => "cursor: pointer;"}
          %a{:href => game_category_run_path(run.game, run.category, run)}
            %td
              = run.game.name
            %td
              = run.category.name
            %td
              %a{:href => game_category_run_path(run.game, run.category, run)} #{run.time}