config/routes.rb
Splitsdb::Application.routes.draw do 
  resources :authentications

  get '/login'  => 'users#new'
  get '/login/twitch'      => 'user_sessions#twitch_login'
  get '/login/twitch/auth' => 'user_sessions#twitch_auth'

  get '/signup' => 'users#new'
  get '/logout' => 'user_sessions#destroy'
  get '/upload' => 'runs#new'
  get '/games'  => 'games#index'
  post '/games' => 'games#create'

  get '/users/:id' => 'users#show', :as => :user
  get '/users/:id/edit' => 'users#edit', :as => :edit_user
  get '/:id/delete' => 'games#destroy'
  get '/:game_id/:category_id/runs/:id/compare/:compare_id' => 'runs#show', :as => :compare
  get '/:game_id/:category_id/runs/:id/download' => 'runs#download_exact'
  get '/:game_id/:category_id/runs/:id/delete' => 'runs#destroy'
  #get '/:game_id/:category_id/runs/:id/download-route' => 'runs#download_blank'
  post '/:game_id/:category_id/runs/:id/edit' => 'runs#edit'

  root 'static_pages#home'

  resources :users do
    resources :runs
  end
  resources :games, :path => ''
  resources :games, :path => '', :only => [] do
    resources :categories, :path => '' do
      resources :runs
    end
    #get :autocomplete_game_name, :on => :collection
  end

  post '/:game_id/:category_id/runs/:id' => 'runs#compare'
#  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :game
  has_many :runs
  validates_presence_of :game
  validates_presence_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # GET /games/:game_id/categories
  # GET /games/:game_id/categories.json
  def index
    @categories = @game.categories
  end

  # GET /games/:game_id/categories/:category_id
  # GET /games/:game_id/categories/:category_id.json
  def show
    @category = Category.find(params[:id])
    @game = Game.friendly.find(params[:game_id])
  end

  # GET /games/:game_id/categories/new
  # GET /games/:game_id/categories/new.json
  def new
    @category = Category.new
    @game = Game.friendly.find(params[:game_id])
  end

  # POST /games/:game_id/categories/create
  # POST /games/:game_id/categories/create.json
  def create
    @game = Game.friendly.find(params[:game_id])
    @category = @game.categories.create(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to game_category_path(@game, @category), notice: 'Category created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @game = Game.friendly.find(params[:game_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
- if @category.errors.any?
  .alert.alert-danger
    %b
      = pluralize(@category.errors.count, "error")
      prohibited this category from being saved:
    %ul
      - @category.errors.full_messages.each do |msg|
        %li= msg
.col-md-6
  .form-group
    %input.form-control.input-lg{:name => "category[name]", :placeholder => "Name", :type => "text"}/
  .form-group
    %textarea.form-control{:name => "category[description]", :placeholder => "Description", :type => "text"}
  .actions
    .btn-group
      %a.btn.btn-default{:href => game_path(@game)} &larr; Back
      %input.btn.btn-default{:name => :commit, :type => :submit, :value => "Create category"}

app/views/categories/index.html.haml
%h1 Categories for #{@game.name}
.col-md-6
  .list-group
    - @categories.each do |category|
      %a.list-group-item{:href => "/games/#{@game.id}/categories/#{category.id}"}
        %h4.list-group-item-heading #{category.name}
        %p.list-group-item-text #{category.description}

app/views/categories/new.html.haml
%h1 New category for #{@game.name}
= form_for @category, url: game_category_path(@game, @category) do |f|
  = render 'form'

app/views/categories/show.html.haml
.col-md-12
  %h1=@game.name
.col-md-3
  - if @game.cover.present?
    %img.img-responsive.thumbnail{alt: @game.name, src: "#{@game.cover}", width: 350}
  - else
    %a.thumbnail{href: edit_game_path, style: 'height: 357px; width: 350px; font-size: 200px; text-align: center;  text-decoration: none;'} +
.col-md-9
  %ul.nav.nav-tabs{style: "border-bottom: none;"}
    - @game.categories.each do |category|
      %li{class: "#{'active' if @category.id == category.id}"}
        %a{href: game_category_path(@game, category)} #{category.name}
    %li.pull-right
      %a{href: new_game_category_path(@game)} + Add category
  .panel.panel-default
    %table.table.table-striped.table-hover{style: "border-top: none;"}
      %tr{style: "border-top: none;"}
        %td{style: "border-top: none;"}
          %b="User"
        %td{style: "border-top: none;"}
          %b="Finish time"
      - if @category
        - if @category.runs.empty?
          %tr
            %td{colspan: 2}
              %i
                Nobody has uploaded any runs for this category.
        - @category.runs.each do |run|
          %tr{onclick: "document.location = '#{game_category_run_path(run.game, run.category, run)}'", style: "cursor: pointer;"}
            %a{href: game_category_run_path(run.game, run.category, run)}
              %td
                = run.user.name
              %td
                %a{href: game_category_run_path(run.game, run.category, run)} #{run.time}
        - if current_user.present?
          %tr{onclick: "document.location = '#{new_game_category_run_path(@game, @category)}'", style: "cursor: pointer;"}
            %td{colspan: 2}
              %a{href: new_game_category_run_path(@game, @category)}
                + Upload a run for this category
      - else
        %tr
          %td{colspan: 2}
            %i
              #{@game.name} has no categories.