config/routes.rb
Splitsdb::Application.routes.draw do 
  resources :authentications

  get '/login'  => 'users#new'
  get '/login/twitch'      => 'user_sessions#twitch_login'
  get '/login/twitch/auth' => 'user_sessions#twitch_auth'

  get '/signup' => 'users#new'
  get '/logout' => 'user_sessions#destroy'
  get '/upload' => 'runs#new'
  get '/games'  => 'games#index'
  post '/games' => 'games#create'

  get '/users/:id' => 'users#show', :as => :user
  get '/users/:id/edit' => 'users#edit', :as => :edit_user
  get '/:id/delete' => 'games#destroy'
  get '/:game_id/:category_id/runs/:id/compare/:compare_id' => 'runs#show', :as => :compare
  get '/:game_id/:category_id/runs/:id/download' => 'runs#download_exact'
  get '/:game_id/:category_id/runs/:id/delete' => 'runs#destroy'
  #get '/:game_id/:category_id/runs/:id/download-route' => 'runs#download_blank'
  post '/:game_id/:category_id/runs/:id/edit' => 'runs#edit'

  root 'static_pages#home'

  resources :users do
    resources :runs
  end
  resources :games, :path => ''
  resources :games, :path => '', :only => [] do
    resources :categories, :path => '' do
      resources :runs
    end
    #get :autocomplete_game_name, :on => :collection
  end

  post '/:game_id/:category_id/runs/:id' => 'runs#compare'
#  match '/auth/:provider/callback' => 'authentications#create'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title splitsdb
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "autocomplete-rails.js"
    = csrf_meta_tags
  %body
    %div#dropzone
      %nav.navbar-custom.navbar-default.navbar-static-top{role: "navigation"}
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} splitsdb
        .collapse.navbar-collapse.navbar-ex1-collapse
          %ul.nav.navbar-nav
            %li{class: "#{'active' if current_page?(root_path)}"}
              %a{href: root_path} Home
            %li{class: "#{'active' if current_page?(games_path)}"}
              %a{href: games_path} Games
          %ul.nav.navbar-nav.navbar-right
            - if current_user_session
              %li{class: "#{'active' if current_page?(user_path(current_user))}"}
                %a#user{href: user_path(current_user), 'data-toggle' => :tooltip, title: current_user.name, 'data-placement' => :left}
                  .glyphicon.glyphicon-user
                  = current_user.name
              %li
                %a#logout{href: logout_path, 'data-toggle' => :tooltip, :title => "Log out", 'data-placement' => :left}
                  .glyphicon.glyphicon-log-out
                  Log out
            - else
              %li{class: "#{'active' if current_page?(login_path) or current_page?(signup_path)}"}
                %a{href: login_path} Log in / sign up
      .container
        - if notice
          .alert.alert-success#notice
            .glyphicon.glyphicon-heart
            = notice
        - if alert
          .alert.alert-danger#alert
            .glyphicon.glyphicon-exclamation-sign
            = alert
        = yield
      :javascript
        //$('#user').tooltip();
        //$('#logout').tooltip();
        $('#download').popover({
          html : true,
          container: 'body',
          content: function() {
            return $('#download-popover').html();
          }
        })
        $('#compare').popover({
          html : true,
          container: 'body',
          content: function() {
            return $('#compare-popover').html();
          }
        })
        $('.breakdown').popover({
          html : true,
          container: 'body',
        })
%footer{style: 'margin-bottom: 40px; margin-right: 20px;'}
  %small.pull-right
    .glyphicon.glyphicon-bullhorn
    Find a bug?
    %a{href: 'mailto:qhiiyr@gmail.com'} Let me know!